//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeuLanche.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientesValorVigencia
    {
        public short SequencialIngrediente { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime Inicio { get; set; }
        public Nullable<System.DateTime> Fim { get; set; }
    }
}
