//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeuLanche.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanchesIngredientes
    {
        public System.Guid Id { get; set; }
        public int Sequencial { get; set; }
        public short SequencialLanche { get; set; }
        public short SequencialIngrediente { get; set; }
        public short Quantidade { get; set; }
    }
}
