//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeuLanche.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocoes
    {
        public System.Guid Id { get; set; }
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public System.DateTime InicioVigencia { get; set; }
        public System.DateTime FimVigencia { get; set; }
        public Nullable<bool> Ativo { get; set; }
    }
}
